---
#Install Python before doing anything else
- hosts: all
  remote_user: ubuntu  
  gather_facts: False
  sudo: yes
  
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: tag_{{tag}}_{{value}}
  vars:
    tag: env
    value: stage
  remote_user: ubuntu  
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    # create a directory if it doesn't exist
    - name: Create Direcory for project
      file:
        path: /var/www/hello-world2
        state: directory
        mode: 0755        

    - name: copy hello_world
      copy:
          src: index.html
          dest: /var/www/hello-world2
          owner: www-data
          group: www-data
          mode: 0644

    - name: copy apache2.conf
      copy:
          src: hello.conf
          dest: /etc/apache2/sites-available/
          owner: www-data
          group: www-data
          mode: 0644          
          
    - name: Delete Apache Default site
      file:
          path: /etc/apache2/sites-enabled/000-default.conf
          state: absent

    - name: Enable port in apache2
      lineinfile:
          name: /etc/apache2/ports.conf
          line: 'Listen 81'

    - name: run e3mod
      command: a2ensite hello   
      notify:
          - restart apache2          

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
